# s3 variables
variable "project_name" {}
variable "env_file_bucket_name" {}
variable "env_file_name" {}
variable "block_public_acls" {}
variable "block_public_policy" {}
variable "ignore_public_acls" {}
variable "restrict_public_buckets" {}
variable "vpc_id" {}